// Public config schemas for @chainofclaw/soul.
//
// These zod schemas own the shape of the `backup.*` and carrier-specific
// keys that appear in the top-level claw-mem config. The umbrella
// @chainofclaw/claw-mem package composes these with its own meta keys.

import { z } from "zod"

// ──────────────────────────────────────────────────────────────────────────
// Carrier — agent-resurrection daemon config
// ──────────────────────────────────────────────────────────────────────────

export const CarrierPendingRequestSchema = z.object({
  requestId: z.string(),
  agentId: z.string(),
})

export const CarrierConfigSchema = z.object({
  enabled: z.boolean().default(false),
  carrierId: z.string().optional(),
  agentEntryScript: z.string().optional(),
  workDir: z.string().default("/tmp/coc-resurrections"),
  watchedAgents: z.array(z.string()).default([]),
  pendingRequestIds: z.array(CarrierPendingRequestSchema).default([]),
  pollIntervalMs: z.number().int().min(1000).default(60_000),
  readinessTimeoutMs: z.number().int().min(1000).default(86_400_000),
  readinessPollMs: z.number().int().min(1000).default(30_000),
})

// ──────────────────────────────────────────────────────────────────────────
// Backup — soul backup / recovery config
// ──────────────────────────────────────────────────────────────────────────

export const BackupSemanticSnapshotSchema = z.object({
  enabled: z.boolean().default(true),
  tokenBudget: z.number().int().min(0).default(8000),
  maxObservations: z.number().int().min(0).default(50),
  maxSummaries: z.number().int().min(0).default(10),
})

export const BackupCategoriesSchema = z.object({
  identity: z.boolean().default(true),
  config: z.boolean().default(true),
  memory: z.boolean().default(true),
  chat: z.boolean().default(true),
  workspace: z.boolean().default(true),
  database: z.boolean().default(true),
})

export const BackupConfigSchema = z.object({
  enabled: z.boolean().default(true),
  /** Source directory to back up (the agent's home). Defaults to ~/.openclaw. */
  sourceDir: z.string().default("~/.openclaw"),
  rpcUrl: z.string().default("http://199.192.16.79:28780"),
  ipfsUrl: z.string().default("http://199.192.16.79:28786").describe("IPFS HTTP API. Default = COC testnet node-1 IPFS port (host 28786 → container 5001). Override for mainnet, your own gateway, or local daemon (http://127.0.0.1:5001)."),
  contractAddress: z.string().default("0x1291Be112d480055DaFd8a610b7d1e203891C274").describe("SoulRegistry address. Default = COC testnet deployment; override for mainnet/custom."),
  didRegistryAddress: z.string().default("0x5f3f1dBD7B74C6B46e8c44f98792A1dAf8d69154").describe("DIDRegistry address. Default = COC testnet deployment; override for mainnet/custom."),
  faucetUrl: z.string().default("http://199.192.16.79:3003").describe("Faucet base URL for auto-drip when an EOA is freshly generated by the keystore. Default = COC testnet faucet (10 COC/drip, 24h cooldown). Empty string disables auto-drip."),
  rpcAuthToken: z.string().optional(),
  privateKey: z.string().optional(),
  autoBackup: z.boolean().default(true),
  autoBackupIntervalMs: z.number().int().min(1000).default(3_600_000),
  maxIncrementalChain: z.number().int().min(1).default(10),
  encryptMemory: z.boolean().default(false),
  encryptionPassword: z.string().optional(),
  backupOnSessionEnd: z.boolean().default(true),
  semanticSnapshot: BackupSemanticSnapshotSchema.default({}),
  categories: BackupCategoriesSchema.default({}),
  carrier: CarrierConfigSchema.default({}),
})

/** Umbrella alias — same zod object, exported under the SDK-wide name. */
export const soulConfigSchema = BackupConfigSchema

export type BackupConfig = z.infer<typeof BackupConfigSchema>
export type CarrierConfig = z.infer<typeof CarrierConfigSchema>
export type BackupSemanticSnapshotConfig = z.infer<typeof BackupSemanticSnapshotSchema>
export type BackupCategoriesConfig = z.infer<typeof BackupCategoriesSchema>
