// Public config schemas for @chainofclaw/soul.
//
// These zod schemas own the shape of the `backup.*` and carrier-specific
// keys that appear in the top-level claw-mem config. The umbrella
// @chainofclaw/claw-mem package composes these with its own meta keys.

import { z } from "zod"
import { DEFAULT_CHAIN_ID, SUPPORTED_CHAIN_IDS } from "./manifests/index.ts"

// ──────────────────────────────────────────────────────────────────────────
// Carrier — agent-resurrection daemon config
// ──────────────────────────────────────────────────────────────────────────

export const CarrierPendingRequestSchema = z.object({
  requestId: z.string(),
  agentId: z.string(),
})

export const CarrierConfigSchema = z.object({
  enabled: z.boolean().default(false),
  carrierId: z.string().optional(),
  agentEntryScript: z.string().optional(),
  workDir: z.string().default("/tmp/coc-resurrections"),
  watchedAgents: z.array(z.string()).default([]),
  pendingRequestIds: z.array(CarrierPendingRequestSchema).default([]),
  pollIntervalMs: z.number().int().min(1000).default(60_000),
  readinessTimeoutMs: z.number().int().min(1000).default(86_400_000),
  readinessPollMs: z.number().int().min(1000).default(30_000),
})

// ──────────────────────────────────────────────────────────────────────────
// Backup — soul backup / recovery config
// ──────────────────────────────────────────────────────────────────────────

export const BackupSemanticSnapshotSchema = z.object({
  enabled: z.boolean().default(true),
  tokenBudget: z.number().int().min(0).default(8000),
  maxObservations: z.number().int().min(0).default(50),
  maxSummaries: z.number().int().min(0).default(10),
})

export const BackupCategoriesSchema = z.object({
  identity: z.boolean().default(true),
  config: z.boolean().default(true),
  memory: z.boolean().default(true),
  chat: z.boolean().default(true),
  workspace: z.boolean().default(true),
  database: z.boolean().default(true),
})

export const BackupConfigSchema = z.object({
  enabled: z.boolean().default(true),
  /** Source directory to back up (the agent's home). Defaults to ~/.openclaw. */
  sourceDir: z.string().default("~/.openclaw"),
  /**
   * COC chainId. Selects which deployed-contracts manifest is consulted when
   * `contractAddress` / `didRegistryAddress` are omitted. Defaults to the
   * currently active COC testnet (88780, R3.2). Pass 18780 to target the
   * decommissioned prowl-testnet for archival reads only.
   */
  chainId: z.number().int().default(DEFAULT_CHAIN_ID).describe(
    `COC chainId. Supported: ${SUPPORTED_CHAIN_IDS.join(", ")}. ` +
    `Used to resolve contract addresses from packaged manifests when none are passed explicitly.`,
  ),
  rpcUrl: z.string().default("http://127.0.0.1:28780").describe(
    "COC node JSON-RPC URL. Default = local node on the canonical 28780 port; " +
    "point to a remote validator/observer for hosted access.",
  ),
  ipfsUrl: z.string().default("http://127.0.0.1:5001").describe(
    "IPFS HTTP API URL. Default = local IPFS daemon. Override for your own gateway " +
    "(e.g. http://gateway.example:5001) or a COC node's bundled IPFS.",
  ),
  contractAddress: z.string().regex(/^0x[0-9a-fA-F]{40}$/).optional().describe(
    "SoulRegistry address override. When omitted, resolved at runtime from the " +
    "deployed-contracts manifest for the selected chainId.",
  ),
  didRegistryAddress: z.string().regex(/^0x[0-9a-fA-F]{40}$/).optional().describe(
    "DIDRegistry address override. When omitted, resolved at runtime from the " +
    "deployed-contracts manifest for the selected chainId.",
  ),
  faucetUrl: z.string().default("").describe(
    "Faucet base URL for auto-drip when an EOA is freshly generated by the keystore. " +
    "Default = disabled. Set to your COC testnet faucet URL to enable auto-drip on first use.",
  ),
  rpcAuthToken: z.string().optional(),
  privateKey: z.string().optional(),
  autoBackup: z.boolean().default(true),
  autoBackupIntervalMs: z.number().int().min(1000).default(3_600_000),
  maxIncrementalChain: z.number().int().min(1).default(10),
  encryptMemory: z.boolean().default(false),
  encryptionPassword: z.string().optional(),
  backupOnSessionEnd: z.boolean().default(true),
  semanticSnapshot: BackupSemanticSnapshotSchema.default({}),
  categories: BackupCategoriesSchema.default({}),
  carrier: CarrierConfigSchema.default({}),
})

/** Umbrella alias — same zod object, exported under the SDK-wide name. */
export const soulConfigSchema = BackupConfigSchema

export type BackupConfig = z.infer<typeof BackupConfigSchema>
export type CarrierConfig = z.infer<typeof CarrierConfigSchema>
export type BackupSemanticSnapshotConfig = z.infer<typeof BackupSemanticSnapshotSchema>
export type BackupCategoriesConfig = z.infer<typeof BackupCategoriesSchema>
